services:
  mlflow:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/mlflow/mlflow:latest

        # Instalar el driver de PostgreSQL
        RUN pip install --no-cache-dir psycopg2-binary

        # Definir variables por defecto
        ENV MLFLOW_HOST=0.0.0.0
        ENV MLFLOW_PORT=${MLFLOW_PORT}
        ENV MLFLOW_BACKEND_STORE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-postgres:5432/${POSTGRES_DB}
        ENV MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts

        EXPOSE 5000

        CMD mlflow server \
          --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-postgres:5432/${POSTGRES_DB} \
          --default-artifact-root /mlflow/artifacts \
          --host 0.0.0.0 \
          --port ${MLFLOW_PORT}
    container_name: mlflow-server
    environment:
      - MLFLOW_PORT=${MLFLOW_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${MLFLOW_PORT}:5000"
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    networks:
      - mlflow-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mlflow-net:
    external: true

volumes:
  mlflow_artifacts:


